name: CICD DevOps test case
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aushafy/stockbit-nginx:latest
    - name: Login to docker hub
      run: docker login --username aushafy --password ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Push to registry
      run: docker push aushafy/stockbit-nginx:latest
    - name: AWS SSM Send-Command
      # You may pin to the exact commit or the version.
      # uses: peterkimzz/aws-ssm-send-command@88467a58e8da19dba79c3124344307b417ca0aa4
      uses: peterkimzz/aws-ssm-send-command@v1.1.0
      with:
        # AWS access key id
        aws-access-key-id: AKIA5TQFXSOBL76IVB4W
        # AWS secret access key
        aws-secret-access-key: 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
        # Where EC2 instance is
        aws-region: ap-southeast-1
        # AWS EC2 Instance id or ids
        instance-ids: i-05679be56c8a5b917
        # Bash command yi-05679be56c8a5b917ou want to execute
        command: sudo docker run -d -p 80:80 aushafy/stockbit-nginx:latest
        # Command execution location
        working-directory: /home/ubuntu
        # Comment for Send-Command
        comment: # optional, default is Executed by Github Actions

