name: CICD DevOps test case
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aushafy/stockbit-nginx:latest
    - name: Login to docker hub
      run: docker login --username aushafy --password ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Push to registry
      run: docker push aushafy/stockbit-nginx:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy docker from docker hub
      uses: fifsky/ssh-action@master
      with:
        command: |
          sudo docker run -d -p 80:80 aushafy/stockbit-nginx:latest
        host: ec2-3-0-61-252.ap-southeast-1.compute.amazonaws.com
        user: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY}}
